---

- name: Include json-update
  ansible.builtin.include_tasks: json-update.yml
  vars:
    json_file: "{{ smallstep_rootdir }}/config/ca.json"
    json_file_owner: step
    json_changes:
      - path: json2.db.type
        value: "{{ smallstep_db_type }}"
      - path: json2.db.dataSource
        value: "{{ smallstep_db_datasource }}"
      - path: json2.db.database
        value: "{{ smallstep_db_name }}"
    json_handler: "Restart ca service"
